"""migration_1

Revision ID: 94528eb8c915
Revises: 47b6751d8564
Create Date: 2025-10-23 18:28:31.132587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94528eb8c915'
down_revision: Union[str, Sequence[str], None] = '47b6751d8564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_activities_organization_id_fkey'), 'organization_activities', type_='foreignkey')
    op.drop_constraint(op.f('organization_activities_activity_id_fkey'), 'organization_activities', type_='foreignkey')
    op.create_foreign_key(None, 'organization_activities', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_activities', 'activities', ['activity_id'], ['id'], ondelete='CASCADE')
    op.add_column('organization_phones', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True))
    op.alter_column('organization_phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization_phones', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(op.f('organization_phones_organization_id_fkey'), 'organization_phones', type_='foreignkey')
    op.create_foreign_key(None, 'organization_phones', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_phones_organization_id_fkey', 'organization_phones', type_='foreignkey')
    op.create_foreign_key(op.f('organization_phones_organization_id_fkey'), 'organization_phones', 'organizations', ['organization_id'], ['id'])
    op.alter_column('organization_phones', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('organization_phones', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('organization_phones', 'id')
    op.drop_constraint('organization_activities_organization_id_fkey', 'organization_activities', type_='foreignkey')
    op.drop_constraint('organization_activities_activity_id_fkey', 'organization_activities', type_='foreignkey')
    op.create_foreign_key(op.f('organization_activities_activity_id_fkey'), 'organization_activities', 'activities', ['activity_id'], ['id'])
    op.create_foreign_key(op.f('organization_activities_organization_id_fkey'), 'organization_activities', 'organizations', ['organization_id'], ['id'])